import { EvidenceItem } from '../types';

export const MOCK_EVIDENCE: EvidenceItem[] = [
  {
    id: '1',
    type: 'IMAGE',
    lat: 48.8566,
    lng: 2.3522,
    country: 'France',
    city: 'Paris',
    title: 'Seine Water Levels Critical',
    description: 'Unusually high water levels observed near Pont Neuf following heavy rainfall.',
    tags: ['flood', 'paris', 'climate'],
    thumbnailUrl: 'https://picsum.photos/400/300?random=1',
    fullUrl: 'https://picsum.photos/1200/800?random=1',
    ipfsHash: 'QmX5...',
    xrplTxHash: 'A1B2C3D4...',
    walletAddress: 'rHb9CJAWyB4rj91VRWn96Dzk4115143',
    timestamp: Date.now() - 10000000,
    verified: true,
  },
  {
    id: '2',
    type: 'VIDEO',
    lat: 52.5200,
    lng: 13.4050,
    country: 'Germany',
    city: 'Berlin',
    title: 'Urban Heat Island Effect',
    description: 'Thermal camera footage showing extreme heat retention in concrete structures.',
    tags: ['heat', 'berlin', 'urban'],
    thumbnailUrl: 'https://picsum.photos/400/300?random=2',
    fullUrl: 'https://picsum.photos/1200/800?random=2',
    ipfsHash: 'QmY7...',
    xrplTxHash: 'E5F6G7H8...',
    walletAddress: 'rHb9CJAWyB4rj91VRWn96Dzk4115143',
    timestamp: Date.now() - 5000000,
    verified: true,
  },
  {
    id: '3',
    type: 'IMAGE',
    lat: 41.3851,
    lng: 2.1734,
    country: 'Spain',
    city: 'Barcelona',
    title: 'Beach Pollution',
    description: 'Plastic waste accumulation after the storm.',
    tags: ['pollution', 'barcelona', 'ocean'],
    thumbnailUrl: 'https://picsum.photos/400/300?random=3',
    fullUrl: 'https://picsum.photos/1200/800?random=3',
    ipfsHash: 'QmZ9...',
    xrplTxHash: 'I9J0K1L2...',
    walletAddress: 'rHb9CJAWyB4rj91VRWn96Dzk4115143',
    timestamp: Date.now() - 2000000,
    verified: false,
  },
  {
    id: '4',
    type: 'IMAGE',
    lat: 35.6762,
    lng: 139.6503,
    country: 'Japan',
    city: 'Tokyo',
    title: 'Air Quality Alert',
    description: 'Smog density visualization near Shibuya crossing.',
    tags: ['air', 'tokyo', 'pollution'],
    thumbnailUrl: 'https://picsum.photos/400/300?random=4',
    fullUrl: 'https://picsum.photos/1200/800?random=4',
    ipfsHash: 'QmA1...',
    xrplTxHash: 'M3N4O5P6...',
    walletAddress: 'rHb9CJAWyB4rj91VRWn96Dzk4115143',
    timestamp: Date.now() - 15000000,
    verified: true,
  },
   {
    id: '5',
    type: 'VIDEO',
    lat: -33.8688,
    lng: 151.2093,
    country: 'Australia',
    city: 'Sydney',
    title: 'Coral Bleaching Documentation',
    description: 'Underwater footage from the coast showing recent bleaching events.',
    tags: ['ocean', 'sydney', 'climate'],
    thumbnailUrl: 'https://picsum.photos/400/300?random=5',
    fullUrl: 'https://picsum.photos/1200/800?random=5',
    ipfsHash: 'QmB2...',
    xrplTxHash: 'Q7R8S9T0...',
    walletAddress: 'rHb9CJAWyB4rj91VRWn96Dzk4115143',
    timestamp: Date.now() - 3000000,
    verified: true,
  },
];